### ISSUE TITLE
请教一下，termux安装biber的问题

### ISSUE THREAD

**Issue by hushidong** [lsq/lsq.github.com#1]
兄弟，没找到你联系方式，所以在这里请教，就是我看你之前解决了，termux安装biber的问题，因为我不太熟悉cpan那边，所以想请教一下，该如何安装，盼回复，感谢！

**Comment by hushidong** [comment]
是不是先编译好执行文件然后放到termux中？还是直接在termux中编译？

**Comment by lsq** [comment]
需要先安装perl，然后在termxu自己编译，编译好复制到PATH目录就可以了

**Comment by hushidong** [comment]
先在ttermux里面安装perl包？
你然后安装CPAN（termux手册上有），
在termux中下载biber, 
然后按照biber documents目录里面pdf说明编译
是这样的步骤吧？

**Comment by hushidong** [comment]
兄弟，有时间能不能写个教程，把一些命令列一列。这样后来者就不用重复了解petl怎么安装，cpan怎么安装，biber怎么编译问题了，特别像我这样对于cpan不了解的，学习起来比较困难。感谢！！

**Comment by lsq** [comment]
### 先安装perl
`
pkg install perl
`
`
cpan App::cpanminus
`

### git clone biber
`git clone https://github.com/plk/biber.git`

### 安装依赖文件
`cpanm Module::Build`
`cpanm PAR::Packer`
### 编译
`cd biber`
`perl ./Build.PL`
### 出现相关问题
`Build installdeps`

--------------------------------------
**有问题附上具体错误信息**

**Comment by hushidong** [comment]
太感谢啦！，需要root不，目前卡在cpan App::cpanminus。

**Comment by hushidong** [comment]
错误代码如下

$ cpan App::cpanminus
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/data/data/com.termux/files/home/.cpan/Metadata'
  Database was generated on Wed, 12 Jun 2019 01:17:03 GMT
Running install for module 'App::cpanminus'
Checksum for /data/data/com.termux/files/home/.cpan/sources/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for App::cpanminus
Writing MYMETA.yml and MYMETA.json
  MIYAGAWA/App-cpanminus-1.7044.tar.gz
  /data/data/com.termux/files/usr/bin/perl Makefile.PL -- OK
Running make for M/MI/MIYAGAWA/App-cpanminus-1.7044.tar.gz
  MIYAGAWA/App-cpanminus-1.7044.tar.gz
  make -- NOT OK
  No such file or directory

**Comment by hushidong** [comment]
YAML是啥东西？

**Comment by hushidong** [comment]
先装一下yaml

$ cpan YAML
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/data/data/com.termux/files/home/.cpan/Metadata'
  Database was generated on Wed, 12 Jun 2019 01:17:03 GMT
Running install for module 'YAML'
Checksum for /data/data/com.termux/files/home/.cpan/sources/authors/id/T/TI/TINITA/YAML-1.29.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring T/TI/TINITA/YAML-1.29.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Warning: prerequisite Test::Deep 0 not found.
Warning: prerequisite Test::YAML 1.05 not found.
Generating a Unix-style Makefile
Writing Makefile for YAML
Writing MYMETA.yml and MYMETA.json
  TINITA/YAML-1.29.tar.gz
  /data/data/com.termux/files/usr/bin/perl Makefile.PL -- OK
Running make for T/TI/TINITA/YAML-1.29.tar.gz
---- Unsatisfied dependencies detected during ----
----          TINITA/YAML-1.29.tar.gz         ----
    Test::Deep [build_requires]
    Test::YAML [build_requires]
Running install for module 'Test::Deep'
Checksum for /data/data/com.termux/files/home/.cpan/sources/authors/id/R/RJ/RJBS/Test-Deep-1.128.tar.gz ok
Configuring R/RJ/RJBS/Test-Deep-1.128.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Test::Deep
Writing MYMETA.yml and MYMETA.json

**Comment by hushidong** [comment]
NEILB/Text-Diff-1.45.tar.gz
  /data/data/com.termux/files/usr/bin/perl Makefile.PL -- OK
Running make for N/NE/NEILB/Text-Diff-1.45.tar.gz
---- Unsatisfied dependencies detected during ----
----        NEILB/Text-Diff-1.45.tar.gz       ----
    Algorithm::Diff [requires]
Running install for module 'Algorithm::Diff'
  TYEMQ/Algorithm-Diff-1.1903.tar.gz
  Has already been unwrapped into directory /data/data/com.termux/files/home/.cpan/build/Algorithm-Diff-1.1903-1
  TYEMQ/Algorithm-Diff-1.1903.tar.gz
  Has already been prepared
  TYEMQ/Algorithm-Diff-1.1903.tar.gz
  Could not make: Unknown error

  NEILB/Text-Diff-1.45.tar.gz
  Has already been unwrapped into directory /data/data/com.termux/files/home/.cpan/build/Text-Diff-1.45-1
  NEILB/Text-Diff-1.45.tar.gz
  Has already been prepared
Running make for N/NE/NEILB/Text-Diff-1.45.tar.gz
Warning: Prerequisite 'Algorithm::Diff => 1.19' for 'NEILB/Text-Diff-1.45.tar.gz' failed when processing 'TYEMQ/Algorithm-Diff-1.1903.tar.gz' with 'make => NO'. Continuing, but chances to succeed are limited.
  NEILB/Text-Diff-1.45.tar.gz
  make -- NOT OK
  No such file or directory
  INGY/Test-Base-0.89.tar.gz
  Has already been unwrapped into directory /data/data/com.termux/files/home/.cpan/build/Test-Base-0.89-1
  INGY/Test-Base-0.89.tar.gz
  Has already been prepared
Running make for I/IN/INGY/Test-Base-0.89.tar.gz
Warning: Prerequisite 'Algorithm::Diff => 1.15' for 'INGY/Test-Base-0.89.tar.gz' failed when processing 'TYEMQ/Algorithm-Diff-1.1903.tar.gz' with 'make => NO'. Continuing, but chances to succeed are limited.
Warning: Prerequisite 'Spiffy => 0.40' for 'INGY/Test-Base-0.89.tar.gz' failed when processing 'INGY/Spiffy-0.46.tar.gz' with 'make => NO'. Continuing, but chances to succeed are limited.
Warning: Prerequisite 'Text::Diff => 0.35' for 'INGY/Test-Base-0.89.tar.gz' failed when processing 'NEILB/Text-Diff-1.45.tar.gz' with 'make => NO'. Continuing, but chances to succeed are limited.
  INGY/Test-Base-0.89.tar.gz
  make -- NOT OK
  No such file or directory
Running install for module 'Test::Deep'
  RJBS/Test-Deep-1.128.tar.gz
  Has already been unwrapped into directory /data/data/com.termux/files/home/.cpan/build/Test-Deep-1.128-1
  RJBS/Test-Deep-1.128.tar.gz
  Has already been prepared
  RJBS/Test-Deep-1.128.tar.gz
  Could not make: Unknown error

**Comment by hushidong** [comment]
e-0.89.tar.gz' failed when processing 'INGY/Spiffy-0.46.tar.gz' with 'make => NO'. Continuing, but chances to succeed are limited.
Warning: Prerequisite 'Text::Diff => 0.35' for 'INGY/Test-Base-0.89.tar.gz' failed when processing 'NEILB/Text-Diff-1.45.tar.gz' with 'make => NO'. Continuing, but chances to succeed are limited.
  INGY/Test-Base-0.89.tar.gz
  make -- NOT OK
  No such file or directory
Running install for module 'Test::Deep'
  RJBS/Test-Deep-1.128.tar.gz
  Has already been unwrapped into directory /data/data/com.termux/files/home/.cpan/build/Test-Deep-1.128-1
  RJBS/Test-Deep-1.128.tar.gz
  Has already been prepared
  RJBS/Test-Deep-1.128.tar.gz
  Could not make: Unknown error

  TINITA/Test-YAML-1.07.tar.gz
  Has already been unwrapped into directory /data/data/com.termux/files/home/.cpan/build/Test-YAML-1.07-1
  TINITA/Test-YAML-1.07.tar.gz
  Has already been prepared
Running make for T/TI/TINITA/Test-YAML-1.07.tar.gz
Warning: Prerequisite 'Test::Base => 0.89' for 'TINITA/Test-YAML-1.07.tar.gz' failed when processing 'INGY/Test-Base-0.89.tar.gz' with 'make => NO'. Continuing, but chances to succeed are limited.
  TINITA/Test-YAML-1.07.tar.gz
  make -- NOT OK
  No such file or directory
  TINITA/YAML-1.29.tar.gz
  Has already been unwrapped into directory /data/data/com.termux/files/home/.cpan/build/YAML-1.29-1
  TINITA/YAML-1.29.tar.gz
  Has already been prepared
Running make for T/TI/TINITA/YAML-1.29.tar.gz
Warning: Prerequisite 'Test::Deep => 0' for 'TINITA/YAML-1.29.tar.gz' failed when processing 'RJBS/Test-Deep-1.128.tar.gz' with 'make => NO'. Continuing, but chances to succeed are limited.
Warning: Prerequisite 'Test::YAML => 1.05' for 'TINITA/YAML-1.29.tar.gz' failed when processing 'TINITA/Test-YAML-1.07.tar.gz' with 'make => NO'. Continuing, but chances to succeed are limited.
  TINITA/YAML-1.29.tar.gz
  make -- NOT OK
  No such file or directory
$

**Comment by lsq** [comment]
问题都是No such file or directory. 你看下是不是权限的原因。

**Comment by hushidong** [comment]
好的，谢谢，我再找找原因。

**Comment by hushidong** [comment]
兄弟，经过你的指导终于完成了，并进行了测试，没有问题了。感谢感谢！！

步骤如下

手机小米max2
系统miui 10.2
未root(从实践看不影响安装，尽管安装了proot但没用)

1. 安装 termux(用的pp助手下载，这里头软件比较全)
设置termux权限，允许读写手机存储

2.安装texlive
pkg install texlive
tlmgr install scheme-full

3.编译biber
pkg install clang (用于基础c编译)
apt install make (安装make，否则安装cpanm无法编译)(这两步用于解决后面编译时出现的No such file or directory错误。见 https://github.com/termux/termux-packages/issues/979)
pkg install perl (安装perl，若termux没有默认安装的话)
cpan App::cpanminus (便于安装依赖模块，好处见https://wiki.termux.com/wiki/Perl，如果因为缺少YAML安装失败，那么用命令cpan YAML 先安装YAML)
git clone https://github.com/plk/biber.git （下载biber）
cpanm Module::Build (安装依赖文件)
cpanm PAR::Packer (安装依赖文件，如果因为Archive::Zip失败，那么用cpanm Archive::Zip --force强制安装，然后重新安装)
cd biber（进入biber目录）
perl ./Build.PL （利用自动脚本安装，但肯定会有依赖缺乏，出现问题，利用下一步安装依赖。）
apt-get install libxslt-dev
apt-get install libxml2
apt-get install libiconv
apt-get install libiconv-dev
apt-get install libssh
apt-get install libssh-dev
cpanm ExtUtils::LibBuilder --force
cpanm Text::BibTeX --force
cpanm PkgConfig --force
cpanm XML::LibXML
cpanm XML::LibXML::Simple
pkg install openssl
pkg install openssl-dev
pkg install openssl-tool
cpanm LWP::Protocol::https
mv MYMETA.json META.json
mv MYMETA.yml META.yml
./Build installdeps （安装biber需要的依赖）
./Build test
./Build install

4. 安装biber
./Build install

5.测试tex 编译
cd /storage/emulated/0/a/
latexmk egtest
但会发现texlive中的biblatex刚编译的最新的biber不能配合。那么还要去biblatex下最新的biblatex

6.使用最新的biblatex
cd ~
git clone https://github.com/plk/biblatex.git
cd biblatex
./obuild/build.sh install 3.13 /data/data/com.termux/files/usr/share/texlive/texmf-dist

7.再次测试tex
xelatex egtest
biber egtest
xelatex egtest
成功打开pdf

**Comment by hushidong** [comment]
再次感谢！！ 
@lsq

**Comment by lsq** [comment]
恭喜恭喜！
